### ISSUE TITLE
system.multicall

### ISSUE THREAD

**Issue by Henner** [rpc4django/rpc4django#35]
seems not to be supported, or did I overlook something?
http://mirrors.talideon.com/articles/multicall.html
http://twistedmatrix.com/trac/attachment/ticket/3823/xmlrpc-multicall.patch

**Comment by angvp** [comment]
Hello @Henner since this code is not merged are you still interested on making a patch? i could do it but I do wanna know if you still interested on having this merged?

**Comment by doudz** [comment]
Multicall is now supported since commit https://github.com/rpc4django/rpc4django/commit/21b36db5eea1b3a432191e04c0fa38bfaa3b3e3f
