### ISSUE TITLE
Please upgrade pip repository

### ISSUE THREAD

**Issue by doudz** [rpc4django/rpc4django#44]
the last version on pip is 0.3.0 which doesn't include the last change regarding django 1.9 warning

**Comment by scottlinux** [comment]
Hi, is it possible to make a new release and upgrade the version in pypi?

**Comment by davidfischer** [comment]
I'll try to make a release this week.

I'm not very active in using this project anymore. If you would like to be a maintainer, let me know.

**Comment by doudz** [comment]
I'm using rpc4django a lot this days. I'd be pleased to help maintaining this project.

**Comment by davidfischer** [comment]
Just to be clear, I was thinking we would upgrade the version in pypi based on what's in `master` now. Then I plan to work on #49 (and get Django 1.11 support as well).

**Comment by davidfischer** [comment]
Actually, I'm going to focus on getting #49 merged and then make a release.

**Comment by davidfischer** [comment]
The latest version v0.4.0 has been released to [PyPI](https://pypi.python.org/pypi/rpc4django) and the updated docs are available on [RTFD](http://rpc4django.readthedocs.io/). 

Thanks for all your help and I appreciate you stepping up as a maintainer of the project!

**Comment by doudz** [comment]
Thank you David, I'll do my best :)
