### ISSUE TITLE
include in urls.py does not work any more in django 1.10

### ISSUE THREAD

**Issue by Henner** [rpc4django/rpc4django#45]
(r'^RPC2$', 'rpc4django.views.serve_rpc_request')

is not supported any more.
binding the view directly leads to an infinite loop - at least here in my code:
from rpc4django.views import serve_rpc_request

urlpatterns = [
    # rpc
    url(r'^xmlrpc/$',
        view=serve_rpc_request,
        name='xmlrpc'),
]

so I created a local function to get late import:

def rpcfunc(request):
    from rpc4django.views import serve_rpc_request
    return serve_rpc_request(request)

urlpatterns = [
    # rpc
    url(r'^xmlrpc/$',
        view=rpcfunc,
        name='xmlrpc'),
]

**Comment by davidfischer** [comment]
Would you be interested in putting together a pull request. I should call out that one other user may be working on one in #46.

**Comment by davidfischer** [comment]
This is now resolved in master and will be fixed on PyPI with the next release!
