### ISSUE TITLE
Deprecating 

### ISSUE THREAD

**Issue by enku** [rpc4django/rpc4django#46]
Hi.   I've recently found a few issues when dealing with rpc4django under Python 3.x.  I'm making changes in a fork which I eventually would like to send for a PR.  However I noticed that `setup.py` still supports Django versions from 1.4 and it would significantly simplify the code and test writing I didn't have to support these older versions (e.g. views.get_request_body) could be ridded of entirely.  Would you be ok with only support the versions of Django that upstream supports (e.g. 1.8 - 1.10)?

**Comment by davidfischer** [comment]
I think it is safe to only support supported versions of Django in a new version of rpc4django. Based on [this](https://www.djangoproject.com/download/#supported-versions), that means 1.8+.

**Comment by enku** [comment]
I'll continue along that vein then.

FWIW I'm initially working on an issue where rpc4django does not work correctly on Python 3 when the client posts with a Content-Type header containing a charset parameter.  E.g.  `Content-Type application/xml; charset utf-8`.  There are a couple of reasons for this:

1. Lax parsing of the Content-Type header

2. calling `json.loads()` on the request body which is `bytes` in Python 3 though `json.loads()` requires `str` (actually I think Python 3.6 allows `bytes`).

There are some places in rpc4django where the request body is interpreted as `bytes` (i.e. is decoded) and other places where it is not.  My intention is to totally rip out `views.get_request_body` and just replace it with `request.body` which IIRC is always `bytes` in Python 3.  Since `request.body` isn't available on older, unsupported Djangos I asked if it was ok to drop support.

Also, a separate issue but while we're on the topic:  It appears that none of the existing tests require any Django internals.  I'm writing tests that require some Django bits (e.g. `RequestFactory`).  For this to work the Django test runner needs to handle the tests, but in `setup.py` it's using straight Python to do this. Would it be okay to utilize [django-setuptest](https://github.com/praekelt/django-setuptest) to accomplish this?

**Comment by davidfischer** [comment]
Sorry in my delay in getting back on this. It looks like #47 fixes issues 1 and 2 above. As to the last bit, I'm ok with refactoring the tests and I can understand why you'd want some Django internals. I think it's best in leaving that to a separate PR though.

On a side note, since you're a regular contributor and it seems like you're still using this project (I'm not) would you be interested in some maintainer privileges? If you're up for it, I'm not opposed to adding you to the rpc4django org.

**Comment by enku** [comment]
Sorry for my delayed response as well.  Thank you for merging in my PR.  For the tests I'll probably submit another PR.   

The company I worked for uses rpc4django for a number of services.  As it turns out I am no longer an employee at that company, so my interest in rpc4django has waned as well.  I think they are interested in an official release that supports Django 1.10+ and there is a possibility that I may assist in that.  So in that case more access may be beneficial, but I'll let you know at a later date.

**Comment by davidfischer** [comment]
This has now been released as v0.4.0 and is available on PyPI. Thanks for all your help. If you have any feedback on this version, don't hesitate to send it.
