### ISSUE TITLE
Update pypi

### ISSUE THREAD

**Issue by doudz** [rpc4django/rpc4django#54]
Please update pypi (or add me to pypi maintainer)

**Comment by davidfischer** [comment]
I am happy to add you as a maintainer. To do so, I need your PyPI username. It [doesn't appear](https://pypi.org/user/doudz/) to be the same as your github username.

**Comment by doudz** [comment]
My Pypi username is : Sbastien.Ramage

**Comment by davidfischer** [comment]
You are added on pypi!

**Comment by doudz** [comment]
Many thanks ! :+1:

**Comment by doudz** [comment]
Done ! release 0.5 is on Pypi
