### ISSUE TITLE
documentation on pypi.org displays bad django requirements

### ISSUE THREAD

**Issue by feenes** [rpc4django/rpc4django#62]
On pypi.org, when clicking on the release history of rpc4django,  I see that versions 0.6.1, 0.6.2 and 0.6.3 work with django 1.8+
> RPC4Django has been tested on Mac OS, Linux and Windows.
> 
>     Python 2.7, 3.3+
>     Django 1.8+
>     DefusedXML
>     Docutils (optional)

However when using pip install of any abover versions, I get a warning, that above versions require django>=1.9

> ERROR: rpc4django 0.6.1 has requirement Django>=1.9, but you'll have django 1.8.19 which is incompatible.

**Comment by doudz** [comment]
Thanks for pointing this out
Support for Django 1.8 has been dropped since release 0.5
https://github.com/rpc4django/rpc4django/commit/0740421aef42c420587f7eaf93d971518179db15
